### ISSUE TITLE
Make pelias SDK respect errors coming back

### ISSUE THREAD

**Issue by msmollin** [pelias/pelias-ios-sdk#42]
Need to improve error handling. The following makes the SDK crash.

``````
JSONDictionary! {
    meta =     {
        "status_code" = 429;
        version = 1;
    };
    results =     {
        error =         {
            message = "Queries per second exceeded: Queries exceeded (6 allowed).";
            type = QpsExceededError;
        };
    };
}```
``````

**Comment by missinglink** [comment]
I copied a couple of the rate-limiter error messages in to docs page: https://mapzen.com/documentation/search/api-keys-rate-limits/

see also: https://mapzen.com/documentation/search/http-status-codes/
